// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteChat(ctx context.Context, id int64) error
	GetChatByID(ctx context.Context, id int64) (Chat, error)
	GetMessageByID(ctx context.Context, id int64) (Message, error)
	ListChats(ctx context.Context) ([]Chat, error)
	ListMessagesByChatID(ctx context.Context, chatID int64) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
