// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"time"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chat (name, created_at)
VALUES (?, ?) RETURNING id, name, created_at
`

type CreateChatParams struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, arg.Name, arg.CreatedAt)
	var i Chat
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (chat_id, role, content, created_at)
VALUES (?, ?, ?, ?) RETURNING id, chat_id, role, content, created_at
`

type CreateMessageParams struct {
	ChatID    int64     `json:"chat_id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ChatID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chat
WHERE id = ?
`

func (q *Queries) DeleteChat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChat, id)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, name, created_at
FROM chat
WHERE id = ?
`

func (q *Queries) GetChatByID(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, chat_id, role, content, created_at
FROM message
WHERE id = ?
`

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listChats = `-- name: ListChats :many
SELECT id, name, created_at
FROM chat
ORDER BY created_at DESC
`

func (q *Queries) ListChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChatID = `-- name: ListMessagesByChatID :many
SELECT id, chat_id, role, content, created_at
FROM message
WHERE chat_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByChatID(ctx context.Context, chatID int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
